### ISSUE TITLE
Snils validation is incorrect for some numbers

### ISSUE THREAD

**Issue by madk1nd** [kdmatrosov/validation-codes#1]
If you will check some of this SNILS numbers - ("134 940 005 39", "914-561-751 11"), you will see that result of `checkSnils` function is false. But online snils validation services show that this numbers are totally valid. For example you can check this one - [validate snils online](https://proverk.ru/snils/), or this one [validate snils online](https://kontragent.info/calcs/inia). I think that maybe something is wrong with your checkSnils algorithm.

**Comment by kdmatrosov** [comment]
You are right that these options are correct. But keep in mind that the function expects a certain format (999-999-999 00). I [added](https://github.com/kdmatrosov/validation-codes/commit/8efe8ddfba56aec8ec45b963a68779245fd09727) your options to the tests (they pass as valid). There is also a new function that takes into account only the checksum without format analysis
